root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./build/tmp/backend.exe ./cmd/backend.go"
entrypoint = "build/tmp/backend.exe"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "build", "logs", "tmp", "vendor"]
include_dir = []
exclude_file = []
log = "logs/air.log"
delay = 1000                                               # ms
stop_on_error = true
send_interrupt = false
kill_delay = 500                                           # ms

[env]
APP_ENV = "dev"
APP_USER = "air"

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true
